### PR TITLE
upgrading to tone@13.8.21

### LINKED ISSUE #309: update tone.js dependency
A few issues are related to the fact that this project relies on a old version of tone.js which was since improved and bugs/dependencies fixed. https://github.com/Tonejs/Tone.js/blob/c023181579d55bac110b9d369f79aa5acd275499/CHANGELOG.md#1349

#56 #294 should all be fixed if we can update tone.js @notwaldorf mentioned issues trying to update so it might be trickier than it sounds.

### PR DESCRIPTION
**Pull request by tambien**
I was able to fix the clicking issue in previous versions of tone@^13.4.9. This doesn't introduce any API changes. 

Should resolve #309 and address #56.

### CODE REVIEW

**Comment by notwaldorf** [comment]
sweet! let me test this real quick!

**Comment by notwaldorf** [comment]
So I listened to a lot of outputs and compared them to https://tensorflow.github.io/magenta-js/music/demos/player.html and friends. I thiiiiink the synth from this patch sounds a bit more attack-y (like comes in louder on every step), but it's on every note and it's predictable, and synths sound alien anyway so i think this might be fine. 

There's also a realistic chance I've gone crazy and imagining this because listening to synth twinkle twinkle 20+ times does that to you.

@adarob can you patch this locally and give it a listen too? and if it's fine we can merge this! 🎉🎉🎉🎉

**Comment by tambien** [comment]
oh yeah you're totally right. i accidentally set the envelope.attack to 0.001 when the default used to be 0.005. I'll remove that line so it'll just remain at the default

**Comment by cannoneyed** [comment]
@adarob @tambien @mattetti 
Just wanted to inject myself real quick in here since it seems like we're all working on the same thing! One thing, @tambien, that may or may not be an issue is that this implementation only creates one PolySynth voice for all instruments in a sequence - this may or may not be an issue (since it's 10 voice polyphonic), and it may not be worth going through all the trouble of pre-instantiating voices like my PR

https://github.com/tensorflow/magenta-js/pull/327

I'd lean towards using this solution, since it's a lot simpler, and having more than 10 voices of the same oscillator playing in a sequence just seems like something that probably doesn't need to be supported anyway.

**Comment by tambien** [comment]
@cannoneyed could also easily make that number larger like 20 if this is an issue.

**Comment by cannoneyed** [comment]
@adarob @notwaldorf  Y'alls call... personally, I'm imagining 20 concurrent oscillators playing every voice in a piece sounding rather.... messy. Capping it at some sensible number like 10 or 16 (because binary) is probably the best tradeoff between what the user expects vs performance

**Comment by notwaldorf** [comment]
could also make that value protected, and you can overriding if you really want to by extending the class

**Comment by cannoneyed** [comment]
Also, can verify that this sounds great. Awesome quick work @tambien!!!

**Comment by notwaldorf** [comment]
yup, that envelope fix makes them sound normal again!

**Comment by mattetti** [comment]
Amazing 😍🙌🎆

**Comment by notwaldorf** [comment]
Thanks!

**Comment by notwaldorf** [comment]
Released this as 1.10.0 🎉🎉🎉

**Comment by adarob** [comment]
Woohoo!!

**Pull request merged**
