### PR TITLE
Add new 4-bar melody model.

### PR DESCRIPTION
**Pull request by adarob**

### CODE REVIEW

**Comment by adarob** [comment]
@teropa, this new checkpoint directory contains an `attribute_vecs.json` file with vectors going in the positive direction for each attribute.

**Comment by teropa** [comment]
Cool, I'll take it for a spin!

**Comment by adarob** [comment]
Just FYI, the attribute vectors don't work quite as well on this model as
in the paper since it is a shrunken version of the model to reduce the
checkpoint size.

**Comment by teropa** [comment]
The checkpoint at https://storage.googleapis.com/magentadata/js/checkpoints/music_vae/mel_4bar_small_q2 seems to be missing a `config.json`, causing magenta.js to not want to load it

**Comment by adarob** [comment]
Try now!

**Comment by teropa** [comment]
Yesss! Thanks

**Pull request merged**
