### PR TITLE
Add an es6 exploded build that can be used with modules

### PR DESCRIPTION
**Pull request by surma**
As commissioned by @notwaldorf 

(Totally still builds!)

### CODE REVIEW

**Comment by surma** [comment]
This PR now also builds ES6 and puts it in an `es6` folder, analogous to ES5 :)

**Comment by notwaldorf** [comment]
yeah, this hoses the tests, unfortunately

**Comment by notwaldorf** [comment]
I'm re-opening this so I can push to it and test things.

**Comment by notwaldorf** [comment]
Closing again because #335 and how does github work even

**Pull request closed without merging**
