### PR TITLE
Remove more isNullOrUndefined uses and bump version.

### PR DESCRIPTION
**Pull request by adarob**

### CODE REVIEW

**Comment by notwaldorf** [comment]
I think this should be a minor bump — 1.2.0. There’s a bunch of new features added and that’s what semver says to do. :)

**Comment by notwaldorf** [comment]
But there’s also a visualizer and a recorder. Hmmm maybe you shouldn’t do a release then?

**Comment by notwaldorf** [comment]
(release numbers tell people what to expect. This release adds new things, rather than fix existing ones, so it’s a bit weird to mark it as such imo. But I won’t block it or anything, I’m just uhhh offering an opinion)

**Comment by adarob** [comment]
This release is just to fix these bugs and unblock Yotam with the node-tf
stuff.

**Comment by notwaldorf** [comment]
Also I think most of these as long as they’re not numbers could be “if !foo” but I think this is the way safer bet. Anyway, ship it squirrel! :shipit:

**Pull request merged**
