### PR TITLE
Use velocity in drum/synth players

### PR DESCRIPTION
**Pull request by notwaldorf**
Yay! Tone.js already had a thing for this!

### CODE REVIEW

**Comment by notwaldorf** [comment]
@adarob did you hear the clipping though?

**Comment by adarob** [comment]
Where specifically should I listen for clipping?

**Comment by notwaldorf** [comment]
In the last demo (that has each of the drums at a small and big velocity) one of the “loud” drums to me sounds clipped (as in it sorta gets blown out and you don’t hear the drum at all. Or the snare. I don’t know what’s it’s called)

**Comment by notwaldorf** [comment]
(update: the drum doesn't get clipped because of the velocity, but because that drum (46) can't be played in succession quickly)

**Pull request merged**
